from collections.abc import Callable
from typing import Protocol, TypeAlias, runtime_checkable

ObserverT: TypeAlias = Callable[[], None]


@runtime_checkable
class ModelProtocol(Protocol):
    def get_count(self) -> int: ...
    def increment(self) -> None: ...
    def decrement(self) -> None: ...
    def add_observer(self, observer: ObserverT) -> None: ...

    # TODO コメントアウトすると Protocol と実装が不整合になってコケる
    # def invalid(self): ...
